### ISSUE TITLE
Move to JuliaIO?

### ISSUE THREAD

**Issue by stevengj** [stevengj/CRC32.jl#1]
@ararslan, @KristofferC, @mbauman — as discussed [recently on discourse](https://discourse.julialang.org/t/why-crc32c-but-missing-crc32/92075), it would be nice to have a drop-in replacement for the CRC32c stdlib that computes the ordinary CRC-32 checksum.

This is a tiny package that just adds a drop-in replacement for `CRC32c.crc32c` based on zlib's `crc32` function, via `Zlib_jll`.

(Of course, a `crc32` interface could alternatively be be added to CodecZlib.jl, but it seems cleaner to have a separate minimal package if you just want a checksum, not to mention more discoverable.  Since they both depend on Zlib_jll, there's no underlying library duplication.)

**Comment by stevengj** [comment]
@StefanKarpinski, I'm not sure who is the point of contact in the JuliaIO org?

**Comment by ararslan** [comment]
I've made you an owner of JuliaIO, feel free to move this there if you'd like. Personally I think it would be fine for it to live in CodecZlib but your point about discoverability is a good one; somewhat analogously, there are SHA and MD5 checksums available in correspondingly named packages. No strong feelings from me either way though, do what feels right.

**Comment by stevengj** [comment]
Thanks!

**Comment by stevengj** [comment]
Transferred, thanks!
